version: "3.9"
services:
  dev:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../.
        target: /home/app
    networks:
      - dev_network
    tty: true
    stdin_open: true

networks:
  dev_network:
    driver: bridge