version: "3.9"
services:
  dev:
    build: .
    volumes:
      - type: bind
        source: .
        target: /home/app
    networks:
      - dev_network
    tty: true
    stdin_open: true

networks:
  dev_network:
    driver: bridge